### ISSUE TITLE
Migrate JSON dependency from RJSONIO to jsonlite

### ISSUE THREAD

**Issue by joey711** [joey711/biomformat0#2]
Seems like a good idea. Most people say jsonlite is better. I think it would helps us perform "round trip" tests more easily.

**Comment by joey711** [comment]
https://github.com/joey711/biom/issues/13

**Comment by joey711** [comment]
@nosson check this

**Comment by jnpaulson** [comment]
It's a simple change and works for all of the example `biom` file when you trade `RJSONIO::fromJSON` to `jsonlite::fromJSON(biom_file,
                simplifyDataFrame = FALSE,
                simplifyMatrix = FALSE)`

Except for the `rich_sparse_char` matrix. Do we need to allow for character OTU matrices?

``` r
read_biom2 <- function(biom_file){  
    x = try(RJSONIO::fromJSON(biom_file),silent=TRUE)
    return( biom(x) )
}
read_biom3 <- function(biom_file){  
    x = try(jsonlite::fromJSON(biom_file,
                simplifyDataFrame = FALSE,
                simplifyMatrix = FALSE),silent=TRUE)
    return( biom(x) )
}
rich_sparse_char  = system.file("extdata", "rich_sparse_char.biom", package = "biomformat")
x6 = read_biom2(rich_sparse_char)
biom_data(x6)
x6 = read_biom3(rich_sparse_char)
biom_data(x6)
```

**Comment by joey711** [comment]
This last bit has been fixed.

However, one of the big advantages of jsonlite is that it automagically puts tables into matrices or data.frames. The R code in the package that is doing this is most likely less efficient, and more error prone, than what jsonlite is doing. 

Works for now as a stop-gap, but would be much better to leverage these table recognizing tools in jsonlite.

When are we posting to BioC??

**Comment by jnpaulson** [comment]
Well the new package submission deadline just passed, but we can try now and see if they're flexible?

**Comment by joey711** [comment]
Let's try it!

Not a terrible thing if they say 'no' and we get it into devel-mode for the next round, and fix the currently-slow matrix handling on the JSON side.
