### ISSUE TITLE
Numeric values instead of integers when importing biome/HDF5 file in R.

### ISSUE THREAD

**Issue by mafed** [joey711/biomformat0#3]
Hi all,
about importing a _biome_ file in R: when `read_biom` reads a biom/HDF5, abundance data are stored in R as `numeric`s instead of `integer`s, that seems a huge waste of memory IMHO.
With American Gut Project's I went from 9.2GB to 480MB just by casting to integers.

**Comment by joey711** [comment]
I'm a bit rusty on my biom-format specs. Does the file format provide a way to specify that data type in the entries?

The problem with coercing to integers in all cases is that if someone stored non-integer values (transformed counts, hybridization intensities, etc), these values will be truncated and information will be lost. 

I like the suggestion in principle, and I think it addresses most of the expected near-term cases, and I don't think this will be difficult to implement, but I do want to know if there's a way to address this type issue proactively.

Thanks for the post!

joey

**Comment by jnpaulson** [comment]
In the biom-format vs 1 there was a `matrix_element_type` specifically for that reason: [see here](http://biom-format.org/documentation/format_versions/biom-1.0.html).

There is a similar requirement in the `DATATYPE` for vs. 2: [see here](http://biom-format.org/documentation/format_versions/biom-2.1.html).  Where the datatypes can be interpreted as either floats or integers: [see here](https://www.hdfgroup.org/HDF5/release/dttable.html). I don't know if any programs output vs2. biom files as ints, but if they do we can recognize that and store them as such.

**Comment by joey711** [comment]
See new home for this issue, above link.
